### ISSUE TITLE
incompatible with Expo web view

### ISSUE THREAD

**Issue by starboundbunny** [kolking/react-native-crossfade-image#19] opened 2023-10-14 21:39 UTC
Using this module with Expo results in this error when a second image is loaded :

helpers.ts: 8
Uncaught TypeError: react_native_web_dist_exports_Image__WEBPACK_IMPORTED_MODULE_0__.default.resolveAssetSource is not a function

Linked to this error with resolveAssetSource:

https://github.com/expo/expo/issues/10737

**Comment by kolking** [comment] 2023-10-15 08:33
Closing because the issue is not related to this component but rather caused by `react-native-web` implementation of `Image.resolveAssetSource`. There is a [pending issue](https://github.com/necolas/react-native-web/issues/1666) in `react-native-web`.

**Closed by kolking** 2023-10-15 08:33 UTC
